### ISSUE TITLE
is resolution adjustable?

### ISSUE THREAD

**Issue by YukiTrace** [runejs/refactored-client-435#199]
I might just not see it but is there a way to adjust resolution or maximize the screen. I know this was a limitation of the game in that era. But the game is tiny these days. For the future idiot like me how do you adjust resolution. If you can't that's fine though.

**Comment by Promises** [comment]
Open console with the key under ESC, type in resizable and hit enter :)

**Comment by YukiTrace** [comment]
that was fast! thanks I never would have figured that out
